# Generated by Django 2.1 on 2020-02-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('pno', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=32, unique=True)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
